import type { Metadata } from 'next'
import Link from 'next/link'
import { buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'How SenseMap works',
  description: 'How SenseMap estimates restaurant sensory environments from public reviews, and what the estimates can and cannot tell you.',
}

const SECTIONS = [
  {
    title: 'Who SenseMap is for',
    body: 'SenseMap is for anyone who wants to know what a restaurant will feel like before they go — including autistic people, people with sensory processing differences, and families planning outings. It is designed to reduce surprises, not to label anyone.',
  },
  {
    title: 'Where the information comes from',
    body: 'Restaurant names, addresses, hours, photos, and Google ratings come from Google Places. Sensory estimates — noise, lighting, crowding, smell, seating, and best times — are generated by SenseMap from patterns in public review text. We always label which is which.',
  },
  {
    title: 'What the SenseMap Score means',
    body: 'The SenseMap Score (0–100) is our estimate of how calm and predictable a space tends to feel. Higher means lower sensory intensity. It is not a quality rating, and it is separate from the Google star rating.',
  },
  {
    title: 'Confidence levels',
    body: 'Each estimate shows how much evidence is behind it. "High confidence" means many reviews agree. "Limited evidence" means only a few reviews mentioned it, so treat it as a hint rather than a fact.',
  },
  {
    title: 'Limitations',
    body: 'Reviews describe individual visits. Sensory conditions change with the day, time, season, and events like birthdays or sports nights. SenseMap does not diagnose, treat, or make any medical claims. When in doubt, call ahead.',
  },
]

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 md:py-16">
      <h1 className="font-serif text-4xl font-medium tracking-tight text-balance">How SenseMap works</h1>
      <p className="mt-4 text-lg leading-relaxed text-muted-foreground text-pretty">
        Plain-language estimates of what a restaurant feels like, with the evidence shown every time.
      </p>
      <div className="mt-10 flex flex-col gap-8">
        {SECTIONS.map((s) => (
          <section key={s.title}>
            <h2 className="text-xl font-medium">{s.title}</h2>
            <p className="mt-2 leading-relaxed text-foreground/80">{s.body}</p>
          </section>
        ))}
      </div>
      <Link href="/explore" className={cn(buttonVariants({ size: 'lg' }), 'mt-12 h-11 rounded-xl px-5')}>
        Explore Fremont restaurants
      </Link>
    </div>
  )
}
