/**
 * SenseMap data model.
 *
 * Google Places data (`place`) and SenseMap-generated estimates (`sensory`)
 * are intentionally kept in separate objects so the two are never conflated.
 */

export type DataSource = 'google' | 'demo'

export type Confidence = 'high' | 'medium' | 'limited'

export type NoiseLevel = 'very-quiet' | 'quiet' | 'moderate' | 'loud'
export type LightingLevel = 'dim' | 'soft' | 'moderate' | 'bright'
export type CrowdingLevel = 'low' | 'moderate' | 'high'
export type SmellLevel = 'low' | 'moderate' | 'strong'
export type IntensityLevel = 'low' | 'moderate' | 'high'
export type SeatingOption = 'quiet-seating' | 'booths' | 'outdoor' | 'private'
export type TimeWindow = 'morning' | 'lunch' | 'afternoon' | 'dinner' | 'late-evening'

export type SensoryFactorKey = 'noise' | 'lighting' | 'crowding' | 'smell' | 'seating' | 'intensity'

export interface PlacePhoto {
  url: string
  alt: string
  attribution?: string
}

/** Fields sourced from Google Places (or the demo stand-in). */
export interface PlaceInfo {
  placeId: string
  name: string
  address: string
  neighborhood?: string
  latitude: number
  longitude: number
  photos: PlacePhoto[]
  cuisine: string
  categories: string[]
  priceLevel?: 1 | 2 | 3 | 4
  googleRating: number | null
  reviewCount: number
  hours: string[]
  mapsUrl?: string
}

export interface SensoryFactor<L extends string> {
  level: L
  /** Human-friendly label, e.g. "Quiet → Moderate". */
  label: string
  summary: string
  confidence: Confidence
}

export interface SeatingFactor {
  options: SeatingOption[]
  label: string
  summary: string
  confidence: Confidence
}

export interface HourlyEstimate {
  /** 24h clock hour. */
  hour: number
  level: IntensityLevel
}

export interface ReviewExcerpt {
  text: string
  /** `google-review` excerpts are verbatim from Google; `illustrative` excerpts are demo-only. */
  kind: 'google-review' | 'illustrative'
  author?: string
  relativeTime?: string
}

export interface EvidenceItem {
  id: string
  factor: SensoryFactorKey | 'timing'
  statement: string
  /** Number of reviews/sources that mention this pattern. */
  mentions: number
  excerpts: ReviewExcerpt[]
}

/** Fields generated by SenseMap analysis. Never a Google value. */
export interface SensoryProfile {
  /** Human-readable name of the AI model that produced this profile, when LLM analysis ran. */
  aiProvider?: string
  /** 0–100. Higher = calmer, more predictable sensory environment. */
  senseMapScore: number
  noise: SensoryFactor<NoiseLevel>
  lighting: SensoryFactor<LightingLevel>
  crowding: SensoryFactor<CrowdingLevel>
  smell: SensoryFactor<SmellLevel>
  seating: SeatingFactor
  sensoryIntensity: SensoryFactor<IntensityLevel>
  bestTimes: HourlyEstimate[]
  bestWindows: TimeWindow[]
  bestTimeLabel: string
  evidence: EvidenceItem[]
  confidence: Confidence
  analyzedReviewCount: number
  method: 'demo-curated' | 'review-keyword-v1' | 'llm-v1'
  analyzedAt: string
}

export interface Restaurant {
  id: string
  source: DataSource
  place: PlaceInfo
  sensory: SensoryProfile
}

export interface RestaurantFilters {
  query: string
  noise: NoiseLevel[]
  lighting: LightingLevel[]
  crowding: CrowdingLevel[]
  smell: SmellLevel[]
  seating: SeatingOption[]
  intensity: IntensityLevel[]
  bestTime: TimeWindow[]
}

/** JSON body of `GET /api/places/search` (docs/DATA_POLICY.md §6, Phase 2). */
export interface PlacesSearchResponse {
  source: DataSource
  query: string
  pageSize: number
  places: PlaceInfo[]
  /** Google's continuation token for the next page; null on the last page. */
  nextPageToken: string | null
}

/** JSON body of `GET /api/places/[placeId]`. */
export interface PlaceDetailResponse {
  source: DataSource
  restaurant: Restaurant
}

// ---------------------------------------------------------------------------
// App-owned data (Phase 3 — docs/DATA_POLICY.md D1/D8). Never Google content.
// ---------------------------------------------------------------------------

/** A place a user saved — keyed by Place ID only. */
export interface SavedPlace {
  placeId: string
  createdAt: string
}

/** A visitor's own sensory note about a place — stored only with consent. */
export interface SensoryFeedback {
  id: string
  placeId: string
  factor: SensoryFactorKey
  note: string | null
  visitTime: string | null
  consent: boolean
  createdAt: string
}

export interface SavedPlacesResponse {
  savedPlaces: SavedPlace[]
}

export interface SavePlaceResponse {
  saved: SavedPlace
  alreadySaved: boolean
}

export interface RemovePlaceResponse {
  removed: boolean
}

export interface FeedbackListResponse {
  feedback: SensoryFeedback[]
}

export interface FeedbackCreatedResponse {
  feedback: SensoryFeedback
}
